<?php
/**
 * *********************************************************
 * 
 * @author cluries
 * @link http://cdbit.com
 * @version 1.0
 * @copyright 2012 http://cdbit.com All rights reserved
 * 
 * *********************************************************
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo $this->importCss('template/default/style.css') ?>
<title>Project Tw2other</title>
</head>
<body>

<div id="message">
	<div id="messageface<?php echo $this->face ?>">&nbsp;</div>
	<div id="dis">
		<?php echo $this->message; ?>
	</div>
</div>	

<div id="navt2o">
<hr />
<div style="height:15px;clear:both;"></div>	
<a href="https://github.com/cluries/tw2other">Project Tw2other</a>
<em><?php echo runTime() ?></em>
<a href="https://twitter.com/cluries"><strong>@cluries</strong></a>
</div>
</body>
</html>